name:                control-systems
version:             0.1.0.0
github:              "tyehle/control-systems"
license:             BSD3
author:              "Tobin Yehle"
maintainer:          "tobinyehle@gmail.com"
copyright:           "2019 Tobin Yehle"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tyehle/control-systems#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- JuicyPixels
- GLFW-b
- gloss
- gloss-rendering
- GLUT
- mtl
- OpenGLRaw
- vector

library:
  source-dirs: src

executables:
  control-systems-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - control-systems

tests:
  control-systems-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - control-systems
